"""initial schema

Revision ID: e9e7bd67d341
Revises: 
Create Date: 2025-06-02 14:54:06.659273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e7bd67d341'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxmox_credentials',
    sa.Column('proxmox_id', sa.Integer(), nullable=False),
    sa.Column('proxmox_user', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.String(length=50), nullable=False),
    sa.Column('token_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('proxmox_id')
    )
    op.create_index(op.f('ix_proxmox_credentials_proxmox_id'), 'proxmox_credentials', ['proxmox_id'], unique=False)
    op.create_table('vm_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_vm_roles_role_id'), 'vm_roles', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('proxmox_credentials_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proxmox_credentials_id'], ['proxmox_credentials.proxmox_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('login_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('logout_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_activity', sa.TIMESTAMP(), nullable=False),
    sa.Column('valid_until', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('vms',
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('vmname', sa.String(length=50), nullable=False),
    sa.Column('vm_ip', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.String(length=50), nullable=False),
    sa.Column('vm_specs', sa.JSON(), nullable=True),
    sa.Column('born_place', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['vm_roles.role_id'], ),
    sa.PrimaryKeyConstraint('vm_id'),
    sa.UniqueConstraint('vmname')
    )
    op.create_index(op.f('ix_vms_vm_id'), 'vms', ['vm_id'], unique=False)
    op.create_table('attack_instructions',
    sa.Column('instructions_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.vm_id'], ),
    sa.PrimaryKeyConstraint('instructions_id')
    )
    op.create_index(op.f('ix_attack_instructions_instructions_id'), 'attack_instructions', ['instructions_id'], unique=False)
    op.create_table('webapp_logs',
    sa.Column('logs_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('activity_made', sa.String(length=400), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.vm_id'], ),
    sa.PrimaryKeyConstraint('logs_id')
    )
    op.create_index(op.f('ix_webapp_logs_logs_id'), 'webapp_logs', ['logs_id'], unique=False)
    op.create_table('attack_targets',
    sa.Column('attack_target_id', sa.Integer(), nullable=False),
    sa.Column('attack_instruction_id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=20), nullable=False),
    sa.Column('attack_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['attack_instruction_id'], ['attack_instructions.instructions_id'], ),
    sa.PrimaryKeyConstraint('attack_target_id')
    )
    op.create_index(op.f('ix_attack_targets_attack_target_id'), 'attack_targets', ['attack_target_id'], unique=False)
    op.create_table('log_analytics',
    sa.Column('logs_analytics_id', sa.Integer(), nullable=False),
    sa.Column('web_logs_id', sa.Integer(), nullable=False),
    sa.Column('attack_instruction_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attack_instruction_id'], ['attack_instructions.instructions_id'], ),
    sa.ForeignKeyConstraint(['web_logs_id'], ['webapp_logs.logs_id'], ),
    sa.PrimaryKeyConstraint('logs_analytics_id')
    )
    op.create_index(op.f('ix_log_analytics_logs_analytics_id'), 'log_analytics', ['logs_analytics_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_analytics_logs_analytics_id'), table_name='log_analytics')
    op.drop_table('log_analytics')
    op.drop_index(op.f('ix_attack_targets_attack_target_id'), table_name='attack_targets')
    op.drop_table('attack_targets')
    op.drop_index(op.f('ix_webapp_logs_logs_id'), table_name='webapp_logs')
    op.drop_table('webapp_logs')
    op.drop_index(op.f('ix_attack_instructions_instructions_id'), table_name='attack_instructions')
    op.drop_table('attack_instructions')
    op.drop_index(op.f('ix_vms_vm_id'), table_name='vms')
    op.drop_table('vms')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vm_roles_role_id'), table_name='vm_roles')
    op.drop_table('vm_roles')
    op.drop_index(op.f('ix_proxmox_credentials_proxmox_id'), table_name='proxmox_credentials')
    op.drop_table('proxmox_credentials')
    # ### end Alembic commands ###
